const dokumenData = [
  {
    no: 1,
    nama: "Masterplan Smart City Kota Bogor",
    keterangan: "Visi, strategi, dan rencana aksi untuk pembangunan Smart City di Kota Bogor.",
    kategori: "SOP",
    tahun: 2022,
    link: "/path/to/dokumen1.pdf",
  },
  {
    no: 2,
    nama: "Rencana Induk Pengembangan E-Government 2014-2018",
    keterangan: "Panduan strategis pengembangan teknologi informasi di lingkungan Pemerintah Kota Bogor.",
    kategori: "data aplikasi",
    tahun: 2014,
    link: "/path/to/dokumen2.pdf",
  },
  {
    no: 3,
    nama: "Penetapan Rencana Kinerja Pemerintah Kota Bogor",
    keterangan: "Dokumen penetapan Rencana Kinerja (RK) tahunan untuk Pemerintah Kota Bogor.",
    kategori: "MANUAL SIMRAL KOTA BOGOR",
    tahun: 2023,
    link: "/path/to/dokumen3.pdf",
  },
  {
    no: 4,
    nama: "SOP Pemasangan dan Penggantian Perangkat Jaringan",
    keterangan: "Standar Operasional Prosedur untuk instalasi dan maintenance infrastruktur jaringan.",
    kategori: "SOP",
    tahun: 2021,
    link: "/path/to/dokumen4.pdf",
  },
  {
    no: 5,
    nama: "Instruksi Presiden No. 3 Tahun 2003",
    keterangan: "Tentang Kebijakan dan Strategi Nasional Pengembangan E-Government.",
    kategori: "Regulasi",
    tahun: 2003,
    link: "/path/to/dokumen5.pdf",
  },
  {
    no: 6,
    nama: "Panduan Umum Tata Kelola TIK Nasional",
    keterangan: "Peraturan menteri tentang pedoman tata kelola TIK di institusi pemerintahan.",
    kategori: "MASTERPLAN SMART CITY KOTA BOGOR",
    tahun: 2016,
    link: "/path/to/dokumen6.pdf",
  },
  {
    no: 7,
    nama: "Modul SIMRAL: Pengisian Pendapatan",
    keterangan: "Panduan teknis untuk mencatat transaksi penerimaan daerah di aplikasi SIMRAL.",
    kategori: "Panduan Aplikasi",
    tahun: 2020,
    link: "/path/to/dokumen7.pdf",
  },
  {
    no: 8,
    nama: "Modul SIMRAL: Login & Hak Akses",
    keterangan: "Penjelasan mengenai manajemen pengguna dan grup hak akses dalam aplikasi SIMRAL.",
    kategori: "Panduan Aplikasi",
    tahun: 2020,
    link: "/path/to/dokumen8.pdf",
  },
  {
    no: 9,
    nama: "Laporan Akuntabilitas Kinerja Instansi Pemerintah (LAKIP) 2023",
    keterangan: "Laporan pertanggungjawaban kinerja Diskominfo selama tahun 2023.",
    kategori: "Kinerja",
    tahun: 2024,
    link: "/path/to/dokumen9.pdf",
  },
  {
    no: 10,
    nama: "SOP Penanganan Insiden Keamanan Siber",
    keterangan: "Prosedur standar dalam menanggapi dan mengatasi insiden keamanan siber.",
    kategori: "SOP",
    tahun: 2022,
    link: "/path/to/dokumen10.pdf",
  }
];

export default dokumenData;